### PR TITLE
Validation: fix out-of-bounds access when content ends in a string

### LINKED ISSUE #156: Fuzz testing
Hello, i am evaluating the use of CBOR as serialization format and is now checking this implementation.  I made a fuzz testing suite from the example in examples/simplereader.c. I have been running it for 10 hours now without any findings. I made a fork and added a fuzzing suite setup i have been using earlier: https://github.com/sijohans/tinycbor/tree/fuzz-test/fuzz-test

I also was looking at fuzzing the function *cbor_value_validate*. I am not really sure how the indented use case for that function is. This is how my test case looks like:
```c
bool fuzz_one_input(const uint8_t *data, size_t size)
{
    CborParser parser;
    CborValue it;
    CborError err = cbor_parser_init(data, size, 0, &parser, &it);
    if (err == CborNoError) {
        err = cbor_value_validate(&it, CborValidateStrictest);
    }
    return (err == CborNoError);
}
```

When using it like this, the fuzzing tools will detect some crashes. If feeding this input (hex representation here):
```
90808080879296808080809a80808064fafafa000700fa000000fa6438300264
```

And then running it with valgrind i can find some more
```sh
$ valgrind ./build_debug/fuzz_validate < output/fuzz_validate/crashes_all/id:000009,sig:06,src:000119+000159,op:splice,rep:8
==6185== Memcheck, a memory error detector
==6185== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==6185== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==6185== Command: ./build_debug/fuzz_validate
==6185==
==6185== Invalid read of size 1
==6185==    at 0x10B636: _cbor_value_extract_number (cborparser.c:169)
==6185==    by 0x10E9F4: validate_number (cborvalidation.c:305)
==6185==    by 0x10FB87: validate_value (cborvalidation.c:564)
==6185==    by 0x10F4E9: validate_container (cborvalidation.c:468)
==6185==    by 0x10FA0E: validate_value (cborvalidation.c:535)
==6185==    by 0x10F4E9: validate_container (cborvalidation.c:468)
==6185==    by 0x10FA0E: validate_value (cborvalidation.c:535)
==6185==    by 0x10F4E9: validate_container (cborvalidation.c:468)
==6185==    by 0x10FA0E: validate_value (cborvalidation.c:535)
==6185==    by 0x10F4E9: validate_container (cborvalidation.c:468)
==6185==    by 0x10FA0E: validate_value (cborvalidation.c:535)
==6185==    by 0x10F4E9: validate_container (cborvalidation.c:468)
==6185==  Address 0x4ba2060 is 0 bytes after a block of size 32 alloc'd
==6185==    at 0x483777F: malloc (vg_replace_malloc.c:299)
==6185==    by 0x110111: afl_read (main_entry.c:33)
==6185==    by 0x11019D: main (main_entry.c:63)
==6185==
==6185==
==6185== HEAP SUMMARY:
==6185==     in use at exit: 0 bytes in 0 blocks
==6185==   total heap usage: 6 allocs, 6 frees, 2,356 bytes allocated
==6185==
==6185== All heap blocks were freed -- no leaks are possible
==6185==
==6185== For counts of detected and suppressed errors, rerun with: -v
==6185== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

Is that the intended use case of the  *cbor_value_validate* function? What else functions would be a nice approach for fuzz testing?

### PR DESCRIPTION
**Pull request by thiagomacieira**
We can only validate_number() if we know that we have a number to
validate in the first place. If we've reached the end of our string, the
content that follows is not necessarily a number (it could be a Break
byte). More importantly, we could reach the end of the buffer.

This issue was masked by the way we provided data to the parser. It
always came from read-only memory becausee of QByteArray::fromRawData(),
so valgrind never caught any issues. Using QByteArray directly wouldn't
have helped because it always inserts a terminating null byte, which
always validates as a correct number (unsigned 0) and fails to trigger
valgrind.

So we need to use malloc() directly to make Valgrind complain. And there
was already a test that did:

==26543== Invalid read of size 1
==26543==    at 0x483EA10: memmove (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==26543==    by 0x43CEEA: read_bytes_unchecked (cborinternal_p.h:239)
==26543==    by 0x43CFEC: extract_number_checked (cborinternal_p.h:286)
==26543==    by 0x43D3E9: validate_number (cborvalidation.c:304)
==26543==    by 0x43DC7B: validate_value (cborvalidation.c:551)
==26543==    by 0x43DE8C: cbor_value_validate (cborvalidation.c:645)
==26543==    by 0x4328D2: tst_Parser::strictValidation() (tst_parser.cpp:1637)
==26543==    by 0x434632: tst_Parser::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (tst_parser.moc:291)
==26543==    by 0x4C0B36D: QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (qmetaobject.cpp:2310)
==26543==    by 0x48673E9: QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (qmetaobject.h:122)
==26543==    by 0x4860256: QTest::TestMethods::invokeTestOnData(int) const (qtestcase.cpp:922)
==26543==    by 0x4860D4B: QTest::TestMethods::invokeTest(int, char const*, QTest::WatchDog*) const (qtestcase.cpp:1121)
==26543==  Address 0x61c4db1 is 0 bytes after a block of size 1 alloc'd
==26543==    at 0x483777F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==26543==    by 0x403891: ParserWrapper::allocateMemory(unsigned long) (tst_parser.cpp:181)
==26543==    by 0x436898: ParserWrapper::init(QByteArray const&) (tst_parser.cpp:126)
==26543==    by 0x432712: tst_Parser::strictValidation() (tst_parser.cpp:1634)
==26543==    by 0x434632: tst_Parser::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (tst_parser.moc:291)
==26543==    by 0x4C0B36D: QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (qmetaobject.cpp:2310)
==26543==    by 0x48673E9: QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const (qmetaobject.h:122)
==26543==    by 0x4860256: QTest::TestMethods::invokeTestOnData(int) const (qtestcase.cpp:922)
==26543==    by 0x4860D4B: QTest::TestMethods::invokeTest(int, char const*, QTest::WatchDog*) const (qtestcase.cpp:1121)
==26543==    by 0x4862083: QTest::TestMethods::invokeTests(QObject*) const (qtestcase.cpp:1465)
==26543==    by 0x4862C14: QTest::qRun() (qtestcase.cpp:1903)
==26543==    by 0x48626C3: QTest::qExec(QObject*, int, char**) (qtestcase.cpp:1792)
==26543==
PASS   : tst_Parser::strictValidation(bytearray-0)

This commit goes further and makes it so an out-of-bounds access will
cause a pagefault.

Fixes #156.

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>

### CODE REVIEW

**Comment by thiagomacieira** [comment]
Please review.

File: tests/parser/tst_parser.cpp [hunk 1]
```diff
@@ -101,6 +112,101 @@ private slots:
...
+        memcpy(data, ptr, len);
+        return cbor_parser_init(data, len, flags, &parser, &first);
+    }
+    uint8_t *begin() { return data; }
+    uint8_t *end()   { return data + len; }
+
+    uint8_t *allocateMemory(size_t);
+    void freeMemory();
+
+    static const size_t PageSize = 4096;
```
Comment (lpereira) [inline tests/parser/tst_parser.cpp]: Is it good to assume 4096 is always the size of a page for portable code? Shouldn't you get it from sysconf(_SC_PAGESIZE)?

File: tests/parser/tst_parser.cpp [hunk 2]
```diff
@@ -101,6 +112,101 @@ private slots:
...
+    if (shouldUseMmap()) {
+        size_t alloc = mmapAllocation(n);
+#if defined(Q_OS_UNIX)
+        realdata = mmap(nullptr, alloc, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
+        Q_ASSERT_X(realdata != MAP_FAILED, "allocateMemory", "mmap failed!");
+
+        // mark last page inaccessible
+        uint8_t *ptr = static_cast<uint8_t *>(realdata);
+        ptr += alloc - PageSize;
+        mprotect(ptr, PageSize, PROT_NONE);
```
Comment (lpereira) [inline tests/parser/tst_parser.cpp]: I like this trick of using mmap()+mprotect() to enforce a fence

File: tests/parser/tst_parser.cpp [hunk 3]
```diff
@@ -1560,18 +1659,17 @@ void tst_Parser::validation_data()
 void tst_Parser::validation()
 {
     QFETCH(QByteArray, data);
-    QFETCH(int, flags);
+    QFETCH(int, flags);;
```
Comment (lpereira) [inline tests/parser/tst_parser.cpp]: Stray ;

**Comment by lpereira** [comment]
Patch looks good to me, but there are a few nits. Comments inline.

File: tests/parser/tst_parser.cpp (hunk 1 above)
Comment (thiagomacieira) [reply tests/parser/tst_parser.cpp]: tinycbor is portable to a lot more systems than its tests are. I really don't expect the tests to be run on anything except x86 and maybe ARM.

File: tests/parser/tst_parser.cpp (hunk 2 above)
Comment (thiagomacieira) [reply tests/parser/tst_parser.cpp]: It is optional. Set environment variable PARSER_NO_MMAP=1 and it'll use `malloc`. I used that so I get a complete picture with valgrind.

File: tests/parser/tst_parser.cpp (hunk 3 above)
Comment (thiagomacieira) [reply tests/parser/tst_parser.cpp]: Fixed.

File: tests/parser/tst_parser.cpp (hunk 2 above)
Comment (lpereira) [reply tests/parser/tst_parser.cpp]: Ack.

File: tests/parser/tst_parser.cpp (hunk 1 above)
Comment (lpereira) [reply tests/parser/tst_parser.cpp]: Not a big deal then.

**Comment by thiagomacieira** [comment]
Quick ping on the nit fixing.

**Comment by thiagomacieira** [comment]
Yep, thanks, that would be appreciated. It might not have found this specific issue until the tests were changed, but now it should.
